spring:
  application:
    name: demo-rag
  ai:
    vectorstore:
      elasticsearch:
        initialize-schema: true
        index-name: test_hugo_index
        dimensions: 1536
        similarity: cosine
        cloudId: ${ELASTIC_CLOUD_ID}
        apiKey: ${ELASTIC_AUTH_HEADER}
    retry:
      max-attempts: 10
      backoff:
        max-interval: 30000
        initial-interval: 2000ms
        multiplier: 5
    azure:
      openai:
        embedding:
          options:
            deployment-name: ai-knowledge
        chat:
          options:
            deployment-name: gpt-4o
        api-key: ${AZURE_OPENAI_API_KEY:your-azure-openai-api-key-here}
        endpoint: ${AZURE_OPENAI_ENDPOINT:https://your-resource-name.openai.azure.com/}
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    try-it-out-enabled: true
    operations-sorter: method
    tags-sorter: alpha
  api-docs:
    path: /api-docs
    enabled: true
  show-actuator: false


logging:
  level:
    com:
      hseabra: DEBUG
    org:
      springframework:
        ai:
          transformer:
            splitter: INFO
      apache:
        pdfbox: ERROR

