spring:
  application:
    name: demo-rag
  ai:
    vectorstore:
      elasticsearch:
        initialize-schema: true
        index-name: custom-index
        dimensions: 1536
        similarity: cosine
    openai:
      api-key: ${OPENAI_API_KEY:your-openai-api-key-here}
      embedding:
        options:
          model: text-embedding-3-small
          dimensions: 1536
      chat:
        options:
          model: gpt-4o-mini
          temperature: 0.7
    retry:
      max-attempts: 10
      backoff:
        max-interval: 30000
        initial-interval: 2000ms
        multiplier: 5
  elasticsearch:
    uris: http://localhost:9200
    username: elastic
    password: ${ELASTICSEARCH_PASSWORD:changeme}
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    try-it-out-enabled: true
    operations-sorter: method
    tags-sorter: alpha
  api-docs:
    path: /api-docs
    enabled: true
  show-actuator: false


logging:
  level:
    com:
      hseabra: DEBUG
    org:
      springframework:
        ai:
          transformer:
            splitter: INFO

